[package]
name = "sgrep-core"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Core types and traits for sgrep"

[dependencies]
eyre.workspace = true
serde.workspace = true

[lints]
workspace = true
